@startuml 图书借阅系统数据库表图

package "library_borrow_system 数据库" {

  entity "用户表 (User)" as User {
    <u>id</u>
    --
    name
    pwd
  }

  entity "管理员表 (Admin)" as Admin {
    <u>id</u>
    --
    name
    pwd
  }

  entity "图书表 (Book)" as Book {
    <u>id</u>
    --
    isbn
    title
    author
    isBorrow
  }

  entity "借阅表 (Borrow)" as Borrow {
    <u>borrowid</u>
    --
    <i>userid</i>
    <i>bookid</i>
    borrowdate
    duedate
    returndate
    status
  }

}

User ||--o{ Borrow : "1对多"
Book ||--o{ Borrow : "1对多"

@enduml