@startuml title 图书借阅系统类图（数据库存储版 + GUI界面）

!define PRIVATE -
!define PUBLIC +
!define PROTECTED #
!define STATIC {static}

package "实体类" {
    class User {
        PRIVATE String id
        PRIVATE String userId
        PRIVATE String username
        PRIVATE String password
        
        PUBLIC User()
        PUBLIC User(String username, String password, String userid)
        PUBLIC String getUserId()
        PUBLIC void setUserId(String userId)
        PUBLIC String getUsername()
        PUBLIC void setUsername(String username)
        PUBLIC String getPassword()
        PUBLIC void setPassword(String password)
    }

    class Admin {
        PRIVATE String adminId
        PRIVATE String adminname
        PRIVATE String password
        
        PUBLIC Admin()
        PUBLIC Admin(String adminname, String password, String adminId)
        PUBLIC String getAdminId()
        PUBLIC void setAdminId(String adminId)
        PUBLIC String getAdminrname()
        PUBLIC void setAdminname(String username)
        PUBLIC String getPassword()
        PUBLIC void setPassword(String password)
    }

    class Book {
        PRIVATE String id
        PRIVATE String title
        PRIVATE String author
        PRIVATE String isbn
        PRIVATE boolean isborrow
        PUBLIC Book()
        PUBLIC Book(String title, String author, String isbn)
        PUBLIC String getBookId()
        PUBLIC void setBookId(String bookId)
        PUBLIC String getTitle()
        PUBLIC void setTitle(String title)
        PUBLIC String getAuthor()
        PUBLIC void setAuthor(String author)
        PUBLIC String getIsbn()
        PUBLIC void setIsbn(String isbn)
        PUBLIC boolean setIsBorrow()
        PUBLIC boolean getIsBorrow()
    }

    class BorrowRecord {
        PRIVATE String recordId
        PRIVATE String userId
        PRIVATE String bookId
        PRIVATE Date borrowDate
        PRIVATE Date dueDate
        PRIVATE Date returnDate
        PRIVATE String status
        PRIVATE boolean isoverdue
        
        PUBLIC BorrowRecord()
        PUBLIC BorrowRecord(String userId, String bookId)
        PUBLIC String getRecordId()
        PUBLIC void setRecordId(String recordId)
        PUBLIC String getUserId()
        PUBLIC void setUserId(String userId)
        PUBLIC String getBookId()
        PUBLIC void setBookId(String bookId)
        PUBLIC Date getBorrowDate()
        PUBLIC void setBorrowDate(Date borrowDate)
        PUBLIC Date getDueDate()
        PUBLIC void setDueDate(Date dueDate)
        PUBLIC Date getReturnDate()
        PUBLIC void setReturnDate(Date returnDate)
        PUBLIC String getStatus()
        PUBLIC void setStatus(String status)
        PUBLIC boolean getisOverdue()
        PUBLIC void setisOverdue() 
    }
}
@enduml